### ISSUE TITLE
Anyone worked on Swift 3 compatibility?

### ISSUE THREAD

**Issue by krusche** [kiavashfaisali/KFSwiftImageLoader#10]

**Comment by kiavashfaisali** [comment]
Hello,

A huge v3.0 update is coming by the end of September which will require Xcode 8.0+, Cocoapods 1.0+, Swift 3.0+.

Stay tuned!

**Comment by CarsonC01** [comment]
Hi will this be migrated to support Swift 3? Let me know the branch if this is possible please?

**Comment by kiavashfaisali** [comment]
Hello,

Yes the code for Swift 3.0 migration is complete and working in the "swift_3" branch.

There is some final polish that will be wrapped up in the branch before being merged into master, but it will all be under-the-hood, so feel free to use the branch if you need to.

The cocoapod will be finalized and merged by this Sunday.

Regards,
Kiavash

On Sep 29, 2016 at 12:37 AM, <CarsonC01<mailto:notifications@github.com>> wrote:

Hi will this be migrated to support Swift 3? Let me know the branch if this is possible please?
