### ISSUE TITLE
Swift 4

### ISSUE THREAD

**Issue by oleghnidets** [kiavashfaisali/KFSwiftImageLoader#16]
Hi,
Any updates regarding Swift 4?

I see the branch `swift4.1` but it has minimum deployment target iOS 11.0. 
Can you change to iOS 10.0?

**Comment by kiavashfaisali** [comment]
Hello,

Sorry for the delayed response! I will be reducing the minimum deployment target to iOS 10.0 and I will aim to release the new version by this weekend.

Regards,
Kiavash

**Comment by kiavashfaisali** [comment]
Hello, Swift 5.1 support has been added with release 4.0.
