### ISSUE TITLE
Swift 4.2

### ISSUE THREAD

**Issue by ConfusedVorlon** [kiavashfaisali/KFSwiftImageLoader#17]
Hi,

it would be great if you could do a 4.2 update

thanks

**Comment by kiavashfaisali** [comment]
Hello,

Apologies for the delays.
I also want to do a 4.2 update. I will roll it in with the impending major release, along with optimizations for it. I hope to work on it within this week.

Regards,
Kiavash

**Comment by kiavashfaisali** [comment]
Hello, Swift 5.1 support has been added with release 4.0.
