### ISSUE TITLE
WatchKit Not Available for iOS 13

### ISSUE THREAD

**Issue by mreilly4** [kiavashfaisali/KFSwiftImageLoader#19]
Kiavash,

I updated to XCode 11 for iOS 13 SDK support and now my app won't run.  It is hung up on your WatchKit functions.

Is there a quick fix for this?

Thanks!

**Comment by kiavashfaisali** [comment]
Hello, I've updated the library and I am now pushing out KFSwiftImageLoader 4.0 with Swift 5.1 compatibility and the fix to the above issue. Sorry for the long delay!
