### ISSUE TITLE
Adding ability to load simple UIImage

### ISSUE THREAD

**Issue by edenfisher** [kiavashfaisali/KFSwiftImageLoader#7]
It would be nice to have an ablity to load a simple UIImage and not just UIImageView.
Thanks :)

**Comment by kiavashfaisali** [comment]
Thank you for the suggestion, I agree that would be a good feature :)
I will try and put that into the next release.

**Comment by kiavashfaisali** [comment]
Hello,

Just wanted to provide an update that this will be added to the next release (KFSwiftImageLoader 4.0.0) as I wanted to focus the latest release on Swift 3.0 modernization and updates.

Thank you!
