### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by ValiDraganescu** [kiavashfaisali/KFSwiftImageLoader#8]
I ran the memory leak instrument over my app which uses this image loader. What I found is that this line of code 
`sharedURLCache.removeCachedResponseForRequest(request)`
is frequently leaking memory.

**Comment by kiavashfaisali** [comment]
Hello, thank you for bringing this to my attention.

Unfortunately, there is not much I can do about this, since that line of code you've posted above is part of the NSURLCache API. I suspect this issue will be fixed in a future version of iOS.

Regards,
Kiavash
